services:
  protection-relay:
    build:
      context: .
      dockerfile: config/Dockerfile.protection-relay
    container_name: protection_relay_ied
    networks:
      - process_bus
    ports:
      - "102:102"
      - "8082:8082"
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
      - MMS_PORT=102
      - SIMULATOR_HOST=substation_web_ui
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/102' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  circuit-breaker:
    build:
      context: .
      dockerfile: config/Dockerfile.circuit-breaker
    container_name: circuit_breaker_ied
    networks:
      - process_bus
    ports:
      - "8081:8081"
      - "103:103"
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
    command: ["./circuit-breaker", "eth0"]
    depends_on:
      - protection-relay
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/103' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  hmi-scada:
    build:
      context: .
      dockerfile: config/Dockerfile.hmi-scada
    container_name: hmi_scada
    networks:
      - process_bus
    ports:
      - "8080:8080"
    environment:
      - RELAY_HOST=protection_relay_ied
      - MMS_PORT=102
    depends_on:
      - protection-relay
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  web-interface:
    build:
      context: ./web-interface
    container_name: substation_web_ui
    networks:
      - process_bus
      - station_bus
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - protection-relay
      - circuit-breaker
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/3000' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  process_bus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  station_bus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
