services:
  protection-relay:
    build:
      context: .
      dockerfile: config/Dockerfile.protection-relay
    container_name: protection_relay_ied_bridge
    networks:
      - process_bus
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
      - MMS_PORT=102
    ports:
      - "102:102"
      - "8082:8082"

  circuit-breaker:
    build:
      context: .
      dockerfile: config/Dockerfile.circuit-breaker
    container_name: circuit_breaker_ied_bridge
    networks:
      - process_bus
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
    ports:
      - "103:103"
      - "8081:8081"
    depends_on:
      - protection-relay

  hmi-scada:
    build:
      context: .
      dockerfile: config/Dockerfile.hmi-scada
    container_name: hmi_scada_bridge
    networks:
      - process_bus
    ports:
      - "8080:8080"
    environment:
      - RELAY_HOST=protection_relay_ied_bridge
      - MMS_PORT=102
    depends_on:
      - protection-relay

networks:
  process_bus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24