services:
  # IEC 61850 Logical Node (LN) based services
  protection-relay:
    build:
      context: .
      dockerfile: config/Dockerfile.protection-relay
      args:
        ICD_PATH: config/models/ln_ied.icd
    container_name: protection_relay_ied
    networks:
      - process_bus
    ports:
      - "102:102"
      - "8082:8082"
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
      - MMS_PORT=102
      - SIMULATOR_HOST=substation_web_ui
    volumes:
      - ./logs:/app/logs

  circuit-breaker:
    build:
      context: .
      dockerfile: config/Dockerfile.circuit-breaker
      args:
        ICD_PATH: config/models/ln_breaker.icd
    container_name: circuit_breaker_ied
    networks:
      - process_bus
    ports:
      - "8081:8081"
      - "103:103"
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
    command: ["./circuit-breaker", "eth0"]
    volumes:
      - ./logs:/app/logs

  hmi-scada:
    build:
      context: .
      dockerfile: config/Dockerfile.hmi-scada
    container_name: hmi_scada
    networks:
      - process_bus
    ports:
      - "8080:8080"
    environment:
      - RELAY_HOST=protection_relay_ied
      - MMS_PORT=102
      - BREAKER_HOST=circuit_breaker_ied
      - BREAKER_PORT=103
    depends_on:
      - protection-relay
      - circuit-breaker
    volumes:
      - ./logs:/app/logs

  web-interface:
    build:
      context: ./web-interface
    container_name: substation_web_ui
    networks:
      - process_bus
      - station_bus
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - protection-relay
      - circuit-breaker
    healthcheck:
      # Use wget (present in node:alpine) instead of bash /dev/tcp
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/simulation-data >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  process_bus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  station_bus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
