services:
  protection-relay:
    build:
      context: .
      dockerfile: config/Dockerfile.protection-relay
    container_name: protection_relay_ied
    networks:
      - goose_network
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
    ports:
      - "102:102"
      - "8082:8082"

  circuit-breaker:
    build:
      context: .
      dockerfile: config/Dockerfile.circuit-breaker
    container_name: circuit_breaker_ied
    networks:
      - goose_network
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      - GOOSE_INTERFACE=eth0
    ports:
      - "103:103"
      - "8081:8081"

networks:
  goose_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "goose-br"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: 192.168.100.0/24