services:
  protection-relay:
    build:
      context: .
      dockerfile: config/Dockerfile.protection-relay
    container_name: protection_relay_ied
    networks:
      - goose_macvlan
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - GOOSE_INTERFACE=eth0

  circuit-breaker:
    build:
      context: .
      dockerfile: config/Dockerfile.circuit-breaker
    container_name: circuit_breaker_ied
    networks:
      - goose_macvlan
    privileged: true
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - GOOSE_INTERFACE=eth0

  web-interface:
    build:
      context: ./web-interface
    container_name: substation_web_ui
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  goose_macvlan:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.100/28