name: IEC 61850 CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Run CI Tests
      run: |
        chmod +x scripts/test-ci.sh
        ./scripts/test-ci.sh